[package]
name = "rdkafka"
version = "0.21.0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
repository = "https://github.com/fede1024/rust-rdkafka"
readme = "README.md"
license = "MIT"
description = "Rust wrapper for librdkafka"
keywords = ["kafka", "rdkafka"]
categories = ["api-bindings"]
edition = "2018"

[dependencies]
rdkafka-sys = { path = "rdkafka-sys", version = "1.2.1" }
futures = "0.3"
libc = "0.2.0"
log = "0.4.8"
pin-project = "0.4"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
tokio-executor = "=0.2.0-alpha.6"

[dev-dependencies]
backoff = "0.1.5"
chrono = "0.4.0"
clap = "2.18.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"
rand = "0.3.15"
regex = "1.1.6"
tokio = "=0.2.0-alpha.6"

[features]
default = []

# Enable ssl and sasl support
ssl = ["rdkafka-sys/ssl"]
sasl = ["rdkafka-sys/sasl", "ssl"]

# Use dynamic linking instead of static. Will fail if librdkafka is not installed.
dynamic_linking = ["rdkafka-sys/dynamic_linking"]

# Use external library for lz4. Use internal if not enabled.
external_lz4 = ["rdkafka-sys/external_lz4"]

# Enable support for zstd compression.
zstd = ["rdkafka-sys/zstd"]
zstd-pkg-config = ["rdkafka-sys/zstd-pkg-config"]

cmake_build = ["rdkafka-sys/cmake_build"]
